### ISSUE TITLE
Replace "Favorite" option with "Close"

### ISSUE THREAD

**Issue by brunelli** [dsboger/gnome-shell-extension-app-switcher-actions#1]
I think an option to close all windows for the selected app would be very useful.

The "add/remove from favorites", on the other hand, doesn't have a reason to be there, as it is relative to the dock.

**Comment by dsboger-zz** [comment]
I was trying to reuse the menu used in the dash and app grid, removing what was not relevant for the extension. Turns out it became harder than making a completely new menu. I've pushed a commit that should do what you proposed. It seems to be working here. Could you test it? If everything goes smoothly, I'll release on e.g.o.

Thanks for reporting!

**Comment by brunelli** [comment]
Amazing!

Working as expected 😀
